### ISSUE TITLE
Компонент инпута в oasis-ui

### ISSUE THREAD

**Issue by alexandertumbasov** [OasisUniverse/ui-library#14]
![image](https://user-images.githubusercontent.com/54313798/144604621-0992caee-d85b-4fed-8e7a-da62da24f5fd.png)
https://www.figma.com/file/G0ftDId1GQpFAG8FxbKkhN/%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-(auth-service)?node-id=0%3A1

**Comment by s4d-prince** [comment]
По поводу кнопки отображения пароля. Придумал примерное отображение линии разделяющей, но пока неизвестно как это будет работать. Также не совсем понимаю где хранить логику отображения этой линии, а именно: вшить в сам компонент кнопки, либо же вшить в компоненте инпута после вывода любого элемента массива JSX.Element'ов не являющегося последним по индексу.

**Comment by s4d-prince** [comment]
@alexandertumbasov Выше написал

**Comment by s4d-prince** [comment]
Так же пока не особо известно, но примерное понимание есть, как сделать отображение на короткий промежуток времени пароля. А именно, мне кажется, что можно сделать следующее: по нажатию на кнопку отображения пароля вызвать функцию (обычный колбэк) в котором сначала будут переключаться тип инпута и вид иконки, а далее, после таймаута, всё будет возвращаться к исходному состоянию. Не зажатие, конечно, как ты планировал, но как вариант.

**Comment by alexandertumbasov** [comment]
> Так же пока не особо известно, но примерное понимание есть, как сделать отображение на короткий промежуток времени пароля. А именно, мне кажется, что можно сделать следующее: по нажатию на кнопку отображения пароля вызвать функцию (обычный колбэк) в котором сначала будут переключаться тип инпута и вид иконки, а далее, после таймаута, всё будет возвращаться к исходному состоянию. Не зажатие, конечно, как ты планировал, но как вариант.

https://stackoverflow.com/questions/18584389/listen-to-mouse-hold-event-on-website первая же ссылка

**Comment by alexandertumbasov** [comment]
- [x] убрать крестик у паролей
- [x] фокус убираем
- [x] дописать логику глазика  
- [x] без глазика когда нет value
- [x] убираем errorLabel 
- [x] сделать крестик по макету  
- [x] placeholder 70% opacity 
- [x] вынести логику из компонента <Switcher /> в Input
- [x] переписать additionalElements 
- [x] переписать логику формирования className у Input
